# cloudbuild.yaml — siap deploy ke Cloud Run (public)
substitutions:
  _REGION: asia-southeast2
  _SERVICE: csv-analyzer-api
  _REPO: app-images
  _IMAGE: csv-analyzer
  _PROJECT_ID: $PROJECT_ID

  # param yang enak diatur dari satu tempat
  _CONCURRENCY: "40"
  _MIN_INSTANCES: "1"
  _BUCKET: csv-analyzer-bucket-unique
  _FIRESTORE_COLLECTION: tasks
  _SERVICE_ACCOUNT: csv-analyzer-run-sa@fitai-news-api-463208.iam.gserviceaccount.com
  _OPENAI_SECRET: OPENAI_API_KEY

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA", "."]

- name: gcr.io/cloud-builders/docker
  args: ["push", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA"]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run","deploy","${_SERVICE}",
      "--project","${_PROJECT_ID}",
      "--image","${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA",
      "--region","${_REGION}",
      "--platform","managed",
      "--execution-environment","gen2",
      "--cpu-boost",
      "--ingress","all",
      "--allow-unauthenticated",

      "--memory","8Gi",
      "--cpu","2",
      "--no-cpu-throttling",
      "--concurrency","${_CONCURRENCY}",
      "--timeout","900",
      "--min-instances","${_MIN_INSTANCES}",
      "--port","8080",

      "--service-account","${_SERVICE_ACCOUNT}",

      "--set-env-vars","ENVIRONMENT=production,LOG_LEVEL=INFO,GCS_BUCKET=${_BUCKET},FIRESTORE_COLLECTION=${_FIRESTORE_COLLECTION}",
      "--set-secrets","OPENAI_API_KEY=${_OPENAI_SECRET}:latest"
    ]

images:
- "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA"
